# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ibr', ['core', 'virtual-layer-plus'])
    module.source = [
        'model/ibr-routing-protocol.cc',
		'model/ibr-hostlist-trailer.cc',
		'model/ibr-routing-table.cc',
		'model/ibr-waysegment-table.cc',
		'model/ibr-header.cc',
        'helper/ibr-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ibr')
    module_test.source = [
        'test/ibr-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ibr'
    headers.source = [
        'model/ibr-routing-protocol.h',
		'model/ibr-hostlist-trailer.h',
		'model/ibr-routing-table.h',
		'model/ibr-waysegment-table.h',
		'model/ibr-header.h',
        'model/ibr-region-host-table.h',
		'helper/ibr-helper.h',
		
        ]


    # bld.ns3_python_bindings()

